name: Build Android APK (Buildozer Docker)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-apk:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Pull Buildozer Docker image
        run: docker pull kivy/buildozer:latest

      - name: Run Buildozer in Docker to build APK
        run: |
          docker run --rm \
            -v "${{ github.workspace }}":/home/user/host \
            -w /home/user/host \
            kivy/buildozer:latest \
            /bin/bash -lc "buildozer -v android debug"

      - name: List outputs
        run: ls -la bin || true

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: cam-robo-scan-apk
          path: |
            bin/*.apk
            bin/*.aab
            bin/*.zip
